-- Latimer Core Data Package (collapsed) (ltc-dp-collapsed) 0.1 - PostgreSQL schema
-- Generated by src/build-sql.py from ltc-dp-collapsed/table-schemas/*.json. Do not edit by hand.
--
-- 25 tables: 25 entity tables (with a primary key) and 0 junction tables
-- (two foreign keys, composite primary key). Column names keep the data package field
-- names (quoted, camelCase); table names use underscores in place of hyphens.
--
-- Usage:  psql -d <database> -f ltc-dp-collapsed.sql

BEGIN;

CREATE SCHEMA ltc_dp_collapsed;
COMMENT ON SCHEMA ltc_dp_collapsed IS 'Latimer Core Data Package (collapsed) 0.1 (http://rs.tdwg.org/ltc/ltc-dp-collapsed)';

-- ---------------------------------------------------------------- entity tables
-- Address: A physical address for an organisational unit or person.
CREATE TABLE ltc_dp_collapsed.address (
    "address_pk" text NOT NULL,
    "organisationalUnit_fk" text,
    "person_fk" text,
    "personRole_fk" text,
    "storageLocation_fk" text,
    "addressCountry" text NOT NULL,
    "addressLocality" text,
    "addressRegion" text,
    "addressType" text,
    "postOfficeBoxNumber" text,
    "postalCode" text,
    "streetAddress" text NOT NULL,
    CONSTRAINT address_pkey PRIMARY KEY ("address_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.address IS 'A physical address for an organisational unit or person. [http://rs.tdwg.org/ltc/terms/Address]';
COMMENT ON COLUMN ltc_dp_collapsed.address."address_pk" IS 'A unique identifier for an ltc:Address. [http://example.com/term-pending/addressID]';
COMMENT ON COLUMN ltc_dp_collapsed.address."organisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasAddress]';
COMMENT ON COLUMN ltc_dp_collapsed.address."person_fk" IS 'An identifier for an ltc:Person. [http://rs.tdwg.org/ltc/terms/hasAddress]';
COMMENT ON COLUMN ltc_dp_collapsed.address."personRole_fk" IS 'An identifier for an ltc:PersonRole. [http://rs.tdwg.org/ltc/terms/hasAddress]';
COMMENT ON COLUMN ltc_dp_collapsed.address."storageLocation_fk" IS 'An identifier for an ltc:StorageLocation. [http://rs.tdwg.org/ltc/terms/hasAddress]';
COMMENT ON COLUMN ltc_dp_collapsed.address."addressCountry" IS 'The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code. [https://schema.org/addressCountry]';
COMMENT ON COLUMN ltc_dp_collapsed.address."addressLocality" IS 'The locality in which the street address is, and which is in the region. For example, Mountain View. [https://schema.org/addressLocality]';
COMMENT ON COLUMN ltc_dp_collapsed.address."addressRegion" IS 'The region in which the locality is, and which is in the country. For example, California or another appropriate first-level Administrative division. [https://schema.org/addressRegion]';
COMMENT ON COLUMN ltc_dp_collapsed.address."addressType" IS 'A person or organization can have different addresses, for different purposes. For example, a postal address, a loan address, an address for visits and so on. This property is used to specify the kind of address. [http://rs.tdwg.org/ltc/terms/addressType]';
COMMENT ON COLUMN ltc_dp_collapsed.address."postOfficeBoxNumber" IS 'The post office box number for PO box addresses. [https://schema.org/postOfficeBoxNumber]';
COMMENT ON COLUMN ltc_dp_collapsed.address."postalCode" IS 'The postal code. For example, 94043. [https://schema.org/postalCode]';
COMMENT ON COLUMN ltc_dp_collapsed.address."streetAddress" IS 'The street address. For example, 1600 Amphitheatre Pkwy. [https://schema.org/streetAddress]';

-- Chronometric Age: The age of a specimen or related materials that is generated from a dating assay.
CREATE TABLE ltc_dp_collapsed.chronometric_age (
    "chronometricAge_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "chronometricAgeProtocol" text,
    "chronometricAgeRemarks" text,
    "chronometricAgeUncertaintyInYears" numeric,
    "earliestChronometricAge" numeric,
    "earliestChronometricAgeReferenceSystem" text,
    "latestChronometricAge" numeric,
    "latestChronometricAgeReferenceSystem" text,
    "verbatimChronometricAge" text,
    CONSTRAINT chronometric_age_pkey PRIMARY KEY ("chronometricAge_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.chronometric_age IS 'The age of a specimen or related materials that is generated from a dating assay. [http://rs.tdwg.org/ltc/terms/ChronometricAge]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."chronometricAge_pk" IS 'A unique identifier for an ltc:ChronometricAge. [http://example.com/term-pending/chronometricAgeID]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasChronometricAge]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."chronometricAgeProtocol" IS 'A description of or reference to the methods used to determine the chronometric age. [http://rs.tdwg.org/chrono/terms/chronometricAgeProtocol]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."chronometricAgeRemarks" IS 'Notes or comments about the ChronometricAge. [http://rs.tdwg.org/chrono/terms/chronometricAgeRemarks]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."chronometricAgeUncertaintyInYears" IS 'The temporal uncertainty of the earliestChronometricAge and latestChronometicAge in years. [http://rs.tdwg.org/chrono/terms/chronometricAgeUncertaintyInYears]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."earliestChronometricAge" IS 'The maximum/earliest/oldest possible age of a specimen as determined by a dating method. [http://rs.tdwg.org/chrono/terms/earliestChronometricAge]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."earliestChronometricAgeReferenceSystem" IS 'The reference system associated with the earliestChronometricAge. [http://rs.tdwg.org/chrono/terms/earliestChronometricAgeReferenceSystem]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."latestChronometricAge" IS 'The minimum/latest/youngest possible age of a specimen as determined by a dating method. [http://rs.tdwg.org/chrono/terms/latestChronometricAge]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."latestChronometricAgeReferenceSystem" IS 'The reference system associated with the latestChronometricAge. [http://rs.tdwg.org/chrono/terms/latestChronometricAgeReferenceSystem]';
COMMENT ON COLUMN ltc_dp_collapsed.chronometric_age."verbatimChronometricAge" IS 'The verbatim age for a specimen, whether reported by a dating assay, associated references, or legacy information. [http://rs.tdwg.org/chrono/terms/verbatimChronometricAge]';

-- Collection Status History: A record of current and past statuses of the object group and the reason for status changes.
CREATE TABLE ltc_dp_collapsed.collection_status_history (
    "collectionStatusHistory_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "status" text NOT NULL,
    "statusChangeReason" text,
    "statusType" text NOT NULL,
    CONSTRAINT collection_status_history_pkey PRIMARY KEY ("collectionStatusHistory_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.collection_status_history IS 'A record of current and past statuses of the object group and the reason for status changes. [http://rs.tdwg.org/ltc/terms/CollectionStatusHistory]';
COMMENT ON COLUMN ltc_dp_collapsed.collection_status_history."collectionStatusHistory_pk" IS 'A unique identifier for an ltc:CollectionStatusHistory. [http://example.com/term-pending/collectionStatusHistoryID]';
COMMENT ON COLUMN ltc_dp_collapsed.collection_status_history."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasCollectionStatusHistory]';
COMMENT ON COLUMN ltc_dp_collapsed.collection_status_history."status" IS 'The development status of the collection during a specified period. [http://rs.tdwg.org/ltc/terms/status]';
COMMENT ON COLUMN ltc_dp_collapsed.collection_status_history."statusChangeReason" IS 'An explanation of why the collection transitioned to the value set in the status property. [http://rs.tdwg.org/ltc/terms/statusChangeReason]';
COMMENT ON COLUMN ltc_dp_collapsed.collection_status_history."statusType" IS 'A top-level classification of the different categories of status that can be applied to the collection. [http://rs.tdwg.org/ltc/terms/statusType]';

-- Contact Detail: Details of a method by which an entity such as a Person or OrganisationalUnit may be contacted.
CREATE TABLE ltc_dp_collapsed.contact_detail (
    "contactDetail_pk" text NOT NULL,
    "organisationalUnit_fk" text,
    "person_fk" text,
    "personRole_fk" text,
    "contactDetailCategory" text NOT NULL,
    "contactDetailFunction" text[],
    "contactDetailValue" text NOT NULL,
    CONSTRAINT contact_detail_pkey PRIMARY KEY ("contactDetail_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.contact_detail IS 'Details of a method by which an entity such as a Person or OrganisationalUnit may be contacted. [http://rs.tdwg.org/ltc/terms/ContactDetail]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."contactDetail_pk" IS 'A unique identifier for an ltc:ContactDetail. [http://example.com/term-pending/contactDetailID]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."organisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasContactDetail]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."person_fk" IS 'An identifier for an ltc:Person. [http://rs.tdwg.org/ltc/terms/hasContactDetail]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."personRole_fk" IS 'An identifier for an ltc:PersonRole. [http://rs.tdwg.org/ltc/terms/hasContactDetail]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."contactDetailCategory" IS 'The method of contact to which the contact detail applies. [http://rs.tdwg.org/ltc/terms/contactDetailCategory]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."contactDetailFunction" IS 'A brief label describing the nature of the enquiry or enquiries that are appropriate to direct to the contact detail. [http://rs.tdwg.org/ltc/terms/contactDetailFunction]';
COMMENT ON COLUMN ltc_dp_collapsed.contact_detail."contactDetailValue" IS 'The value of the contact detail, such as the phone number or email address. [http://rs.tdwg.org/ltc/terms/contactDetailValue]';

-- Ecological Context: The ecological and/or biogeographic classification of the region from which objects associated with the ObjectGroup were collected, or where an Event took place.
CREATE TABLE ltc_dp_collapsed.ecological_context (
    "ecologicalContext_pk" text NOT NULL,
    "event_fk" text,
    "objectGroup_fk" text,
    "biogeographicRealm" text,
    "biome" text,
    "biomeType" text,
    "bioregion" text,
    "ecoregion" text,
    "ecosystem" text,
    "habitat" text,
    CONSTRAINT ecological_context_pkey PRIMARY KEY ("ecologicalContext_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.ecological_context IS 'The ecological and/or biogeographic classification of the region from which objects associated with the ObjectGroup were collected, or where an Event took place. [http://rs.tdwg.org/ltc/terms/EcologicalContext]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."ecologicalContext_pk" IS 'A unique identifier for an ltc:EcologicalContext. [http://example.com/term-pending/ecologicalContextID]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasEcologicalContext]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasEcologicalContext]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."biogeographicRealm" IS 'The broadest biogeographic division of Earth''s land and marine surface, based on distributional patterns of terrestrial and marine organisms. [http://rs.tdwg.org/ltc/terms/biogeographicRealm]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."biome" IS 'A biogeographical unit consisting of a biological community that has formed in response to the physical environment in which they are found and a shared regional climate. [http://rs.tdwg.org/ltc/terms/biome]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."biomeType" IS 'A top level classification of the type of biome from which objects were collected or where an event took place. [http://rs.tdwg.org/ltc/terms/biomeType]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."bioregion" IS 'An ecologically and geographically defined area that is smaller than a biogeographic realm, but larger than an ecoregion or an ecosystem. [http://rs.tdwg.org/ltc/terms/bioregion]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."ecoregion" IS 'An ecologically and geographically defined area that is smaller than a bioregion, which in turn is smaller than a biogeographic realm. Ecoregions cover relatively large areas of land or water, and contain characteristic, geographically distinct assemblages of natural communities and species. [http://rs.tdwg.org/ltc/terms/ecoregion]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."ecosystem" IS 'A specific kind of ecological classification that considers all four elements of the definition of ecosystems: a biotic component, an abiotic complex, the interactions between and within them, and the physical space that they occupy. [http://rs.tdwg.org/ltc/terms/ecosystem]';
COMMENT ON COLUMN ltc_dp_collapsed.ecological_context."habitat" IS 'A description of the type of environment in which an organism lives. [http://rs.tdwg.org/ltc/terms/habitat]';

-- Event: An action that occurs at some location during some time.
CREATE TABLE ltc_dp_collapsed.event (
    "event_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "parentEvent_fk" text NOT NULL,
    "eventName" text,
    "samplingProtocol" text[],
    "verbatimEventDate" text,
    CONSTRAINT event_pkey PRIMARY KEY ("event_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.event IS 'An action that occurs at some location during some time. [http://rs.tdwg.org/ltc/terms/Event]';
COMMENT ON COLUMN ltc_dp_collapsed.event."event_pk" IS 'A unique identifier for an ltc:Event. [http://example.com/term-pending/eventID]';
COMMENT ON COLUMN ltc_dp_collapsed.event."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasEvent]';
COMMENT ON COLUMN ltc_dp_collapsed.event."parentEvent_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasParentEvent]';
COMMENT ON COLUMN ltc_dp_collapsed.event."eventName" IS 'The name commonly used to identify or refer to the event. [http://rs.tdwg.org/ltc/terms/eventName]';
COMMENT ON COLUMN ltc_dp_collapsed.event."samplingProtocol" IS 'The names of, references to, or descriptions of the methods or protocols used during an Event. [http://rs.tdwg.org/dwc/terms/samplingProtocol]';
COMMENT ON COLUMN ltc_dp_collapsed.event."verbatimEventDate" IS 'The verbatim original representation of the date and time information for an Event. [http://rs.tdwg.org/dwc/terms/verbatimEventDate]';

-- Geographic Context: The geographic location from which objects associated with the ObjectGroup were collected, or where an Event took place.
CREATE TABLE ltc_dp_collapsed.geographic_context (
    "geographicContext_pk" text NOT NULL,
    "event_fk" text,
    "objectGroup_fk" text,
    "continent" text,
    "country" text,
    "countryCode" text,
    "county" text,
    "island" text,
    "islandGroup" text,
    "locality" text,
    "municipality" text,
    "region" text,
    "stateProvince" text,
    "waterBody" text,
    "waterBodyType" text,
    CONSTRAINT geographic_context_pkey PRIMARY KEY ("geographicContext_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.geographic_context IS 'The geographic location from which objects associated with the ObjectGroup were collected, or where an Event took place. [http://rs.tdwg.org/ltc/terms/GeographicContext]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."geographicContext_pk" IS 'A unique identifier for an ltc:GeographicContext. [http://example.com/term-pending/geographicContextID]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasGeographicContext]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasGeographicContext]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."continent" IS 'The name of the continent in which the Location occurs. [http://rs.tdwg.org/dwc/terms/continent]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."country" IS 'The name of the country or major administrative unit in which the Location occurs. [http://rs.tdwg.org/dwc/terms/country]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."countryCode" IS 'The standard code for the country in which the Location occurs. [http://rs.tdwg.org/dwc/terms/countryCode]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."county" IS 'The full, unabbreviated name of the next smaller administrative region than stateProvince (county, shire, department, etc.) in which the Location occurs. [http://rs.tdwg.org/dwc/terms/county]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."island" IS 'The name of the island on or near which the Location occurs. [http://rs.tdwg.org/dwc/terms/island]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."islandGroup" IS 'The name of the island group in which the Location occurs. [http://rs.tdwg.org/dwc/terms/islandGroup]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."locality" IS 'The specific description of the place. [http://rs.tdwg.org/dwc/terms/locality]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."municipality" IS 'The full, unabbreviated name of the next smaller administrative region than county (city, municipality, etc.) in which the Location occurs. Do not use this term for a nearby named place that does not contain the actual location. [http://rs.tdwg.org/dwc/terms/municipality]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."region" IS 'The name of a spatial region or named place of any size within an individual or multiple administrative areas. [http://rs.tdwg.org/ltc/terms/region]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."stateProvince" IS 'The name of the next smaller administrative region than country (state, province, canton, department, region, etc.) in which the Location occurs. [http://rs.tdwg.org/dwc/terms/stateProvince]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."waterBody" IS 'The name of the water body in which the Location occurs. [http://rs.tdwg.org/dwc/terms/waterBody]';
COMMENT ON COLUMN ltc_dp_collapsed.geographic_context."waterBodyType" IS 'A term that indicates the aquatic order of a waterbody. [http://rs.tdwg.org/ltc/terms/waterBodyType]';

-- Geological Context: Geological information, such as stratigraphy, that qualifies a region or place.
CREATE TABLE ltc_dp_collapsed.geological_context (
    "geologicalContext_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "bed" text,
    "earliestAgeOrLowestStage" text,
    "earliestEonOrLowestEonothem" text,
    "earliestEpochOrLowestSeries" text,
    "earliestEraOrLowestErathem" text,
    "earliestPeriodOrLowestSystem" text,
    "formation" text,
    "group" text,
    "latestAgeOrHighestStage" text,
    "latestEonOrHighestEonothem" text,
    "latestEpochOrHighestSeries" text,
    "latestEraOrHighestErathem" text,
    "latestPeriodOrHighestSystem" text,
    "member" text,
    "supergroup" text,
    CONSTRAINT geological_context_pkey PRIMARY KEY ("geologicalContext_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.geological_context IS 'Geological information, such as stratigraphy, that qualifies a region or place. [http://rs.tdwg.org/ltc/terms/GeologicalContext]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."geologicalContext_pk" IS 'A unique identifier for an ltc:GeologicalContext. [http://example.com/term-pending/geologicalContextID]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasGeologicalContext]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."bed" IS 'The full name of the lithostratigraphic bed from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/bed]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."earliestAgeOrLowestStage" IS 'The full name of the earliest possible geochronologic age or lowest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/earliestAgeOrLowestStage]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."earliestEonOrLowestEonothem" IS 'The full name of the earliest possible geochronologic eon or lowest chrono-stratigraphic eonothem or the informal name (Precambrian) attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/earliestEonOrLowestEonothem]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."earliestEpochOrLowestSeries" IS 'The full name of the earliest possible geochronologic epoch or lowest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."earliestEraOrLowestErathem" IS 'The full name of the earliest possible geochronologic era or lowest chronostratigraphic erathem attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."earliestPeriodOrLowestSystem" IS 'The full name of the earliest possible geochronologic period or lowest chronostratigraphic system attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/earliestPeriodOrLowestSystem]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."formation" IS 'The full name of the lithostratigraphic formation from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/formation]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."group" IS 'The full name of the lithostratigraphic group from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/group]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."latestAgeOrHighestStage" IS 'The full name of the latest possible geochronologic age or highest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/latestAgeOrHighestStage]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."latestEonOrHighestEonothem" IS 'The full name of the latest possible geochronologic eon or highest chrono-stratigraphic eonothem or the informal name (Precambrian) attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/latestEonOrHighestEonothem]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."latestEpochOrHighestSeries" IS 'The full name of the latest possible geochronologic epoch or highest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."latestEraOrHighestErathem" IS 'The full name of the latest possible geochronologic era or highest chronostratigraphic erathem attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/latestEraOrHighestErathem]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."latestPeriodOrHighestSystem" IS 'The full name of the latest possible geochronologic period or highest chronostratigraphic system attributable to the stratigraphic horizon from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/latestPeriodOrHighestSystem]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."member" IS 'The full name of the lithostratigraphic member from which the cataloged item was collected. [http://rs.tdwg.org/dwc/terms/member]';
COMMENT ON COLUMN ltc_dp_collapsed.geological_context."supergroup" IS 'The full name of the lithostratigraphic supergroup from which the cataloged item was collected. [http://rs.tdwg.org/ltc/terms/supergroup]';

-- Identifier: A numeric, textual value, or reference such as an IRI, that can be used to uniquely identify the object to which it is attached.
CREATE TABLE ltc_dp_collapsed.identifier (
    "identifier_pk" text NOT NULL,
    "address_fk" text,
    "chronometricAge_fk" text,
    "collectionStatusHistory_fk" text,
    "contactDetail_fk" text,
    "ecologicalContext_fk" text,
    "event_fk" text,
    "geographicContext_fk" text,
    "geologicalContext_fk" text,
    "latimerCoreScheme_fk" text,
    "measurementOrFact_fk" text,
    "objectClassification_fk" text,
    "objectGroup_fk" text,
    "organisationalUnit_fk" text,
    "person_fk" text,
    "personRole_fk" text,
    "recordLevel_fk" text,
    "reference_fk" text,
    "resourceRelationship_fk" text,
    "role_fk" text,
    "schemeMeasurementOrFact_fk" text,
    "schemeTerm_fk" text,
    "storageLocation_fk" text,
    "taxon_fk" text,
    "identifierSource" text,
    "identifierType" text NOT NULL,
    "identifierValue" text NOT NULL,
    CONSTRAINT identifier_pkey PRIMARY KEY ("identifier_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.identifier IS 'A numeric, textual value, or reference such as an IRI, that can be used to uniquely identify the object to which it is attached. [http://rs.tdwg.org/ltc/terms/Identifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."identifier_pk" IS 'A unique identifier for an ltc:Identifier. [http://example.com/term-pending/identifierID]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."address_fk" IS 'An identifier for an ltc:Address. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."chronometricAge_fk" IS 'An identifier for an ltc:ChronometricAge. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."collectionStatusHistory_fk" IS 'An identifier for an ltc:CollectionStatusHistory. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."contactDetail_fk" IS 'An identifier for an ltc:ContactDetail. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."ecologicalContext_fk" IS 'An identifier for an ltc:EcologicalContext. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."geographicContext_fk" IS 'An identifier for an ltc:GeographicContext. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."geologicalContext_fk" IS 'An identifier for an ltc:GeologicalContext. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."latimerCoreScheme_fk" IS 'An identifier for an ltc:LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."measurementOrFact_fk" IS 'An identifier for an ltc:MeasurementOrFact. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."objectClassification_fk" IS 'An identifier for an ltc:ObjectClassification. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."organisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."person_fk" IS 'An identifier for an ltc:Person. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."personRole_fk" IS 'An identifier for an ltc:PersonRole. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."recordLevel_fk" IS 'An identifier for an ltc:RecordLevel. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."reference_fk" IS 'An identifier for an ltc:Reference. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."resourceRelationship_fk" IS 'An identifier for an ltc:ResourceRelationship. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."role_fk" IS 'An identifier for an ltc:Role. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."schemeMeasurementOrFact_fk" IS 'An identifier for an ltc:SchemeMeasurementOrFact. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."schemeTerm_fk" IS 'An identifier for an ltc:SchemeTerm. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."storageLocation_fk" IS 'An identifier for an ltc:StorageLocation. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."taxon_fk" IS 'An identifier for an ltc:Taxon. [http://rs.tdwg.org/ltc/terms/hasIdentifier]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."identifierSource" IS 'The source or creator of the identifier. [http://rs.tdwg.org/ltc/terms/identifierSource]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."identifierType" IS 'The type and format of the value in the identifier field. [http://rs.tdwg.org/ltc/terms/identifierType]';
COMMENT ON COLUMN ltc_dp_collapsed.identifier."identifierValue" IS 'A textual or numeric identifier, acronym or IRI that provides an unambiguous reference for an entity within a given context. [http://rs.tdwg.org/ltc/terms/identifierValue]';

-- Latimer Core Scheme: A grouping of multiple ObjectGroups for a particular use case, purpose or implementation.
CREATE TABLE ltc_dp_collapsed.latimer_core_scheme (
    "latimerCoreScheme_pk" text NOT NULL,
    "basisOfScheme" text,
    "isDistinctObjects" boolean NOT NULL,
    "schemeName" text NOT NULL,
    CONSTRAINT latimer_core_scheme_pkey PRIMARY KEY ("latimerCoreScheme_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.latimer_core_scheme IS 'A grouping of multiple ObjectGroups for a particular use case, purpose or implementation. [http://rs.tdwg.org/ltc/terms/LatimerCoreScheme]';
COMMENT ON COLUMN ltc_dp_collapsed.latimer_core_scheme."latimerCoreScheme_pk" IS 'A unique identifier for an ltc:LatimerCoreScheme. [http://example.com/term-pending/latimerCoreSchemeID]';
COMMENT ON COLUMN ltc_dp_collapsed.latimer_core_scheme."basisOfScheme" IS 'A summary of the basis or purpose for the LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/basisOfScheme]';
COMMENT ON COLUMN ltc_dp_collapsed.latimer_core_scheme."isDistinctObjects" IS 'A flag to designate whether a physical object may be described by more than one ObjectGroup within the LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/isDistinctObjects]';
COMMENT ON COLUMN ltc_dp_collapsed.latimer_core_scheme."schemeName" IS 'A short descriptive name given to the LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/schemeName]';

-- Measurement or Fact: A measurement of or fact about a class within the standard, or a relationship between the ObjectGroup and an associated class.
CREATE TABLE ltc_dp_collapsed.measurement_or_fact (
    "measurementOrFact_pk" text NOT NULL,
    "chronometricAge_fk" text,
    "collectionStatusHistory_fk" text,
    "ecologicalContext_fk" text,
    "event_fk" text,
    "geographicContext_fk" text,
    "geologicalContext_fk" text,
    "objectClassification_fk" text,
    "objectGroup_fk" text,
    "organisationalUnit_fk" text,
    "person_fk" text,
    "personRole_fk" text,
    "resourceRelationship_fk" text,
    "storageLocation_fk" text,
    "taxon_fk" text,
    "temporalCoverage_fk" text,
    "measurementAccuracy" text,
    "measurementDerivation" text,
    "measurementFactText" text,
    "measurementMethod" text,
    "measurementRemarks" text,
    "measurementType" text,
    "measurementUnit" text,
    "measurementValue" numeric,
    CONSTRAINT measurement_or_fact_pkey PRIMARY KEY ("measurementOrFact_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.measurement_or_fact IS 'A measurement of or fact about a class within the standard, or a relationship between the ObjectGroup and an associated class. [http://rs.tdwg.org/ltc/terms/MeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementOrFact_pk" IS 'A unique identifier for an ltc:MeasurementOrFact. [http://example.com/term-pending/measurementOrFactID]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."chronometricAge_fk" IS 'An identifier for an ltc:ChronometricAge. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."collectionStatusHistory_fk" IS 'An identifier for an ltc:CollectionStatusHistory. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."ecologicalContext_fk" IS 'An identifier for an ltc:EcologicalContext. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."geographicContext_fk" IS 'An identifier for an ltc:GeographicContext. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."geologicalContext_fk" IS 'An identifier for an ltc:GeologicalContext. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."objectClassification_fk" IS 'An identifier for an ltc:ObjectClassification. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."organisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."person_fk" IS 'An identifier for an ltc:Person. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."personRole_fk" IS 'An identifier for an ltc:PersonRole. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."resourceRelationship_fk" IS 'An identifier for an ltc:ResourceRelationship. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."storageLocation_fk" IS 'An identifier for an ltc:StorageLocation. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."taxon_fk" IS 'An identifier for an ltc:Taxon. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."temporalCoverage_fk" IS 'An identifier for an ltc:TemporalCoverage. [http://rs.tdwg.org/ltc/terms/hasMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementAccuracy" IS 'The description of the potential error associated with the measurementValue. [http://rs.tdwg.org/dwc/terms/measurementAccuracy]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementDerivation" IS 'An indicator as to whether the measurement, fact, characteristic, or assertion being applied to the collection was derived from reported figures or aggregated/calculated from underlying data. [http://rs.tdwg.org/ltc/terms/measurementDerivation]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementFactText" IS 'The value of the qualitative fact, characteristic, or assertion being made about the collection. [http://rs.tdwg.org/ltc/terms/measurementFactText]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementMethod" IS 'A description of or reference to (publication, IRI) the method or protocol used to determine the measurement, fact, characteristic, or assertion. [http://rs.tdwg.org/dwc/terms/measurementMethod]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementRemarks" IS 'Comments or notes accompanying the MeasurementOrFact. [http://rs.tdwg.org/dwc/terms/measurementRemarks]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementType" IS 'The nature of the measurement, fact, characteristic, or assertion. [http://rs.tdwg.org/dwc/terms/measurementType]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementUnit" IS 'The units associated with the measurementValue. [http://rs.tdwg.org/dwc/terms/measurementUnit]';
COMMENT ON COLUMN ltc_dp_collapsed.measurement_or_fact."measurementValue" IS 'The value of the measurement, fact, characteristic, or assertion. [http://rs.tdwg.org/dwc/terms/measurementValue]';

-- Object Classification: An informal classification of the type of objects within the ObjectGroup, using a hierarchical structure.
CREATE TABLE ltc_dp_collapsed.object_classification (
    "objectClassification_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "parentObjectClassification_fk" text NOT NULL,
    "isTopParent" boolean,
    "objectClassificationLevel" text,
    "objectClassificationName" text NOT NULL,
    CONSTRAINT object_classification_pkey PRIMARY KEY ("objectClassification_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.object_classification IS 'An informal classification of the type of objects within the ObjectGroup, using a hierarchical structure. [http://rs.tdwg.org/ltc/terms/ObjectClassification]';
COMMENT ON COLUMN ltc_dp_collapsed.object_classification."objectClassification_pk" IS 'A unique identifier for an ltc:ObjectClassification. [http://example.com/term-pending/objectClassificationID]';
COMMENT ON COLUMN ltc_dp_collapsed.object_classification."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasObjectClassification]';
COMMENT ON COLUMN ltc_dp_collapsed.object_classification."parentObjectClassification_fk" IS 'An identifier for an ltc:ObjectClassification. [http://example.com/term-pending/hasParentObjectClassification]';
COMMENT ON COLUMN ltc_dp_collapsed.object_classification."isTopParent" IS 'A flag to indicate that the current instance of ObjectClassification is at the top of the hierarchy represented by multiple nested instances of the class. [http://rs.tdwg.org/ltc/terms/isTopParent]';
COMMENT ON COLUMN ltc_dp_collapsed.object_classification."objectClassificationLevel" IS 'The level of the ObjectClassification in the hierarchy. [http://rs.tdwg.org/ltc/terms/objectClassificationLevel]';
COMMENT ON COLUMN ltc_dp_collapsed.object_classification."objectClassificationName" IS 'A short title describing this ObjectClassification as a class, unit or grouping. [http://rs.tdwg.org/ltc/terms/objectClassificationName]';

-- Object Group: An intentionally grouped set of objects with one or more common characteristics.
CREATE TABLE ltc_dp_collapsed.object_group (
    "objectGroup_pk" text NOT NULL,
    "latimerCoreScheme_fk" text,
    "recordLevel_fk" text,
    "alternativeCollectionName" text[],
    "baseTypeOfObjectGroup" text[] NOT NULL,
    "collectionManagementSystem" text[],
    "collectionName" text,
    "conditionsOfAccess" text[],
    "degreeOfEstablishment" text[],
    "description" text,
    "discipline" text[],
    "isCurrentCollection" boolean,
    "isKnownToContainTypes" boolean,
    "material" text[],
    "objectType" text[],
    "period" text[],
    "preparationType" text[],
    "preservationMethod" text[],
    "preservationMode" text[],
    "typeOfObjectGroup" text[],
    CONSTRAINT object_group_pkey PRIMARY KEY ("objectGroup_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.object_group IS 'An intentionally grouped set of objects with one or more common characteristics. [http://rs.tdwg.org/ltc/terms/ObjectGroup]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."objectGroup_pk" IS 'A unique identifier for an ltc:ObjectGroup. [http://example.com/term-pending/objectGroupID]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."latimerCoreScheme_fk" IS 'An identifier for an ltc:LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/hasObjectGroup]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."recordLevel_fk" IS 'An identifier for an ltc:RecordLevel. [http://rs.tdwg.org/ltc/terms/hasObjectGroup]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."alternativeCollectionName" IS 'One or more short titles different to the one given in ObjectGroup.collectionName used to summarise the collection objects contained within the ObjectGroup. [http://rs.tdwg.org/ltc/terms/alternativeCollectionName]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."baseTypeOfObjectGroup" IS 'High-level terms describing the fundamental nature of objects in the ObjectGroup. [http://rs.tdwg.org/ltc/terms/baseTypeOfObjectGroup]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."collectionManagementSystem" IS 'The collection management system which is used to hold and manage the primary data for the objects contained within the ObjectGroup. [http://rs.tdwg.org/ltc/terms/collectionManagementSystem]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."collectionName" IS 'A short title that summarises the collection objects contained within the ObjectGroup. [http://rs.tdwg.org/ltc/terms/collectionName]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."conditionsOfAccess" IS 'Information about who can access the collection being described or an indication of its security status. [http://rs.tdwg.org/ltc/terms/conditionsOfAccess]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."degreeOfEstablishment" IS 'The degree to which an Organism survives, reproduces, and expands its range at the given place and time. [http://rs.tdwg.org/dwc/terms/degreeOfEstablishment]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."description" IS 'A free text description or narrative about the collection. [http://rs.tdwg.org/ltc/terms/description]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."discipline" IS 'A high level classification of the scientific discipline to which the objects within the collection belong or are related. [http://rs.tdwg.org/ltc/terms/discipline]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."isCurrentCollection" IS 'A flag to indicate whether the collection still exists as a single entity. [http://rs.tdwg.org/ltc/terms/isCurrentCollection]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."isKnownToContainTypes" IS 'Flag property to indicate that the collection is known to include type specimens. [http://rs.tdwg.org/ltc/terms/isKnownToContainTypes]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."material" IS 'Material denotes the raw substance(s) from which the object is formed, in whole or in part. [http://rs.tdwg.org/ltc/terms/material]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."objectType" IS 'High-level terms for the classification of curated objects. [http://rs.tdwg.org/ltc/terms/objectType]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."period" IS 'Used to describe prehistoric or historic periods. [http://rs.tdwg.org/ltc/terms/period]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."preparationType" IS 'A term used to classify or describe an object that indicates the actions that have been taken upon it and/or the processes it has been put through to prepare it for scientific use or study. [http://rs.tdwg.org/ltc/terms/preparationType]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."preservationMethod" IS 'A term used to classify or describe an object that indicates the primary or most recent action, measure or process that has been used in order to preserve the objects in the collection for long-term storage. [http://rs.tdwg.org/ltc/terms/preservationMethod]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."preservationMode" IS 'The means by which a palaeontological specimen was preserved or created e.g. body, cast, mold, trace fossil, soft parts mineralised etc. [http://rs.tdwg.org/ltc/terms/preservationMode]';
COMMENT ON COLUMN ltc_dp_collapsed.object_group."typeOfObjectGroup" IS 'Additional information that describes the object(s) in the collection. [http://rs.tdwg.org/ltc/terms/typeOfObjectGroup]';

-- Organisational Unit: A unit within an organisational hierarchy which may be at, above or below the institutional level.
CREATE TABLE ltc_dp_collapsed.organisational_unit (
    "organisationalUnit_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "parentOrganisationalUnit_fk" text NOT NULL,
    "organisationalUnitName" text NOT NULL,
    "organisationalUnitType" text NOT NULL,
    CONSTRAINT organisational_unit_pkey PRIMARY KEY ("organisationalUnit_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.organisational_unit IS 'A unit within an organisational hierarchy which may be at, above or below the institutional level. [http://rs.tdwg.org/ltc/terms/OrganisationalUnit]';
COMMENT ON COLUMN ltc_dp_collapsed.organisational_unit."organisationalUnit_pk" IS 'A unique identifier for an ltc:OrganisationalUnit. [http://example.com/term-pending/organisationalUnitID]';
COMMENT ON COLUMN ltc_dp_collapsed.organisational_unit."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasOrganisationalUnit]';
COMMENT ON COLUMN ltc_dp_collapsed.organisational_unit."parentOrganisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasParentOrganisationalUnit]';
COMMENT ON COLUMN ltc_dp_collapsed.organisational_unit."organisationalUnitName" IS 'An official name of the organisational unit in the local language. [http://rs.tdwg.org/ltc/terms/organisationalUnitName]';
COMMENT ON COLUMN ltc_dp_collapsed.organisational_unit."organisationalUnitType" IS 'The type or level of organisational unit within a hierarchy responsible for the management of the collection being described. [http://rs.tdwg.org/ltc/terms/organisationalUnitType]';

-- Person: A person (alive, dead, undead, or fictional).
CREATE TABLE ltc_dp_collapsed.person (
    "person_pk" text NOT NULL,
    "additionalName" text,
    "familyName" text,
    "fullName" text,
    "givenName" text,
    CONSTRAINT person_pkey PRIMARY KEY ("person_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.person IS 'A person (alive, dead, undead, or fictional). [http://rs.tdwg.org/ltc/terms/Person]';
COMMENT ON COLUMN ltc_dp_collapsed.person."person_pk" IS 'A unique identifier for an ltc:Person. [http://example.com/term-pending/personID]';
COMMENT ON COLUMN ltc_dp_collapsed.person."additionalName" IS 'An additional name for a Person, can be used for a middle name. [https://schema.org/additionalName]';
COMMENT ON COLUMN ltc_dp_collapsed.person."familyName" IS 'Family name. In the U.S., the last name of a Person. [https://schema.org/familyName]';
COMMENT ON COLUMN ltc_dp_collapsed.person."fullName" IS 'String of the preferred form of personal name for displaying. [http://rs.tdwg.org/abcd/terms/fullName]';
COMMENT ON COLUMN ltc_dp_collapsed.person."givenName" IS 'Given name. In the U.S., the first name of a Person. [https://schema.org/givenName]';

-- Person Role: A qualified association between a Person or OrganisationalUnit and an entity such as an ObjectGroup or MeasurementOrFact that enables the relationship to be contextualised with a specific role and time period.
CREATE TABLE ltc_dp_collapsed.person_role (
    "personRole_pk" text NOT NULL,
    "person_fk" text NOT NULL,
    "role_fk" text NOT NULL,
    "event_fk" text,
    "objectGroup_fk" text,
    "organisationalUnit_fk" text,
    "recordLevel_fk" text,
    CONSTRAINT person_role_pkey PRIMARY KEY ("personRole_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.person_role IS 'A qualified association between a Person or OrganisationalUnit and an entity such as an ObjectGroup or MeasurementOrFact that enables the relationship to be contextualised with a specific role and time period. [http://rs.tdwg.org/ltc/terms/PersonRole]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."personRole_pk" IS 'A unique identifier for an ltc:PersonRole. [http://example.com/term-pending/personRoleID]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."person_fk" IS 'An identifier for an ltc:Person. [http://rs.tdwg.org/ltc/terms/hasPerson]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."role_fk" IS 'An identifier for an ltc:Role. [http://rs.tdwg.org/ltc/terms/hasRole]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasPersonRole]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasPersonRole]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."organisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasPersonRole]';
COMMENT ON COLUMN ltc_dp_collapsed.person_role."recordLevel_fk" IS 'An identifier for an ltc:RecordLevel. [http://rs.tdwg.org/ltc/terms/hasPersonRole]';

-- Record Level: The machine-actionable information profile for the collection description digital object.
CREATE TABLE ltc_dp_collapsed.record_level (
    "recordLevel_pk" text NOT NULL,
    "isDerivedCollection" boolean,
    "license" text NOT NULL,
    "rights" text,
    "rightsHolder" text,
    CONSTRAINT record_level_pkey PRIMARY KEY ("recordLevel_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.record_level IS 'The machine-actionable information profile for the collection description digital object. [http://rs.tdwg.org/ltc/terms/RecordLevel]';
COMMENT ON COLUMN ltc_dp_collapsed.record_level."recordLevel_pk" IS 'A unique identifier for an ltc:RecordLevel. [http://example.com/term-pending/recordLevelID]';
COMMENT ON COLUMN ltc_dp_collapsed.record_level."isDerivedCollection" IS 'A flag to indicate that the collection description has been generated by aggregating data from one or more underlying datasets of its individual objects. [http://rs.tdwg.org/ltc/terms/isDerivedCollection]';
COMMENT ON COLUMN ltc_dp_collapsed.record_level."license" IS 'A legal document giving official permission to do something with the resource. [http://purl.org/dc/terms/license]';
COMMENT ON COLUMN ltc_dp_collapsed.record_level."rights" IS 'Information about rights held in and over the resource. [http://purl.org/dc/elements/1.1/rights]';
COMMENT ON COLUMN ltc_dp_collapsed.record_level."rightsHolder" IS 'A person or organization owning or managing rights over the resource. [http://purl.org/dc/terms/rightsHolder]';

-- Reference: A reference to external resources and information related to the class.
CREATE TABLE ltc_dp_collapsed.reference (
    "reference_pk" text NOT NULL,
    "chronometricAge_fk" text,
    "collectionStatusHistory_fk" text,
    "ecologicalContext_fk" text,
    "event_fk" text,
    "geographicContext_fk" text,
    "geologicalContext_fk" text,
    "identifier_fk" text,
    "latimerCoreScheme_fk" text,
    "measurementOrFact_fk" text,
    "objectClassification_fk" text,
    "objectGroup_fk" text,
    "organisationalUnit_fk" text,
    "person_fk" text,
    "personRole_fk" text,
    "recordLevel_fk" text,
    "resourceRelationship_fk" text,
    "schemeMeasurementOrFact_fk" text,
    "schemeTerm_fk" text,
    "storageLocation_fk" text,
    "taxon_fk" text,
    "temporalCoverage_fk" text,
    "referenceDetails" text,
    "referenceName" text,
    "referenceType" text,
    "resourceIRI" text,
    CONSTRAINT reference_pkey PRIMARY KEY ("reference_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.reference IS 'A reference to external resources and information related to the class. [http://rs.tdwg.org/ltc/terms/Reference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."reference_pk" IS 'A unique identifier for an ltc:Reference. [http://example.com/term-pending/referenceID]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."chronometricAge_fk" IS 'An identifier for an ltc:ChronometricAge. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."collectionStatusHistory_fk" IS 'An identifier for an ltc:CollectionStatusHistory. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."ecologicalContext_fk" IS 'An identifier for an ltc:EcologicalContext. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."geographicContext_fk" IS 'An identifier for an ltc:GeographicContext. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."geologicalContext_fk" IS 'An identifier for an ltc:GeologicalContext. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."identifier_fk" IS 'An identifier for an ltc:Identifier. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."latimerCoreScheme_fk" IS 'An identifier for an ltc:LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."measurementOrFact_fk" IS 'An identifier for an ltc:MeasurementOrFact. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."objectClassification_fk" IS 'An identifier for an ltc:ObjectClassification. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."organisationalUnit_fk" IS 'An identifier for an ltc:OrganisationalUnit. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."person_fk" IS 'An identifier for an ltc:Person. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."personRole_fk" IS 'An identifier for an ltc:PersonRole. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."recordLevel_fk" IS 'An identifier for an ltc:RecordLevel. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."resourceRelationship_fk" IS 'An identifier for an ltc:ResourceRelationship. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."schemeMeasurementOrFact_fk" IS 'An identifier for an ltc:SchemeMeasurementOrFact. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."schemeTerm_fk" IS 'An identifier for an ltc:SchemeTerm. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."storageLocation_fk" IS 'An identifier for an ltc:StorageLocation. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."taxon_fk" IS 'An identifier for an ltc:Taxon. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."temporalCoverage_fk" IS 'An identifier for an ltc:TemporalCoverage. [http://rs.tdwg.org/ltc/terms/hasReference]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."referenceDetails" IS 'Detailed information about the resource being referenced. [http://rs.tdwg.org/ltc/terms/referenceDetails]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."referenceName" IS 'A name given to a reference. [http://rs.tdwg.org/ltc/terms/referenceName]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."referenceType" IS 'The type of resource being referenced. [http://rs.tdwg.org/ltc/terms/referenceType]';
COMMENT ON COLUMN ltc_dp_collapsed.reference."resourceIRI" IS 'A preferably resolvable IRI providing access to the resource defined in the reference. [http://rs.tdwg.org/ltc/terms/resourceIRI]';

-- Resource Relationship: A relationship of one rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource) to another, or to a simple named concept.
CREATE TABLE ltc_dp_collapsed.resource_relationship (
    "resourceRelationship_pk" text NOT NULL,
    "objectGroup_fk" text,
    "recordLevel_fk" text,
    "relatedResourceID" text,
    "relatedResourceName" text,
    "relatedResourceType" text,
    "relationshipAccordingTo" text[],
    "relationshipEstablishedDate" text,
    "relationshipOfResource" text NOT NULL,
    "relationshipRemarks" text,
    "resourceID" text NOT NULL,
    CONSTRAINT resource_relationship_pkey PRIMARY KEY ("resourceRelationship_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.resource_relationship IS 'A relationship of one rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource) to another, or to a simple named concept. [http://rs.tdwg.org/ltc/terms/ResourceRelationship]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."resourceRelationship_pk" IS 'A unique identifier for an ltc:ResourceRelationship. [http://example.com/term-pending/resourceRelationshipID]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasResourceRelationship]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."recordLevel_fk" IS 'An identifier for an ltc:RecordLevel. [http://rs.tdwg.org/ltc/terms/hasResourceRelationship]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relatedResourceID" IS 'An identifier for a related resource (the object, rather than the subject of the relationship). [http://rs.tdwg.org/dwc/terms/relatedResourceID]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relatedResourceName" IS 'A short textual name for the related resource. [http://rs.tdwg.org/ltc/terms/relatedResourceName]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relatedResourceType" IS 'The class or property within Latimer Core, or class, property or less formal concept outside of the Latimer Core standard, that is represented by the related resource. [http://example.com/term-pending/relatedResourceType]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relationshipAccordingTo" IS 'The source (person, organization, publication, reference) establishing the relationship between the two resources. [http://rs.tdwg.org/dwc/terms/relationshipAccordingTo]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relationshipEstablishedDate" IS 'The date-time on which the relationship between the two resources was established. [http://rs.tdwg.org/dwc/terms/relationshipEstablishedDate]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relationshipOfResource" IS 'The relationship of the resource identified by relatedResourceID to the subject (optionally identified by the resourceID). [http://rs.tdwg.org/ltc/terms/relationshipOfResource]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."relationshipRemarks" IS 'Comments or notes about the relationship between the two resources. [http://rs.tdwg.org/dwc/terms/relationshipRemarks]';
COMMENT ON COLUMN ltc_dp_collapsed.resource_relationship."resourceID" IS 'An identifier for the resource that is the subject of the relationship. [http://rs.tdwg.org/dwc/terms/resourceID]';

-- Role: The function of a Person with respect to an activity or entity.
CREATE TABLE ltc_dp_collapsed.role (
    "role_pk" text NOT NULL,
    "roleName" text,
    CONSTRAINT role_pkey PRIMARY KEY ("role_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.role IS 'The function of a Person with respect to an activity or entity. [http://rs.tdwg.org/ltc/terms/Role]';
COMMENT ON COLUMN ltc_dp_collapsed.role."role_pk" IS 'A unique identifier for an ltc:Role. [http://example.com/term-pending/roleID]';
COMMENT ON COLUMN ltc_dp_collapsed.role."roleName" IS 'A short descriptive name for the role. [http://rs.tdwg.org/ltc/terms/roleName]';

-- Scheme Measurement Or Fact: A type of measurement or fact used by the LatimerCoreScheme, and the rules relating to its application.
CREATE TABLE ltc_dp_collapsed.scheme_measurement_or_fact (
    "schemeMeasurementOrFact_pk" text NOT NULL,
    "latimerCoreScheme_fk" text NOT NULL,
    "isMandatoryMetric" boolean NOT NULL,
    "isRepeatableMetric" boolean NOT NULL,
    "schemeMeasurementType" text NOT NULL,
    CONSTRAINT scheme_measurement_or_fact_pkey PRIMARY KEY ("schemeMeasurementOrFact_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.scheme_measurement_or_fact IS 'A type of measurement or fact used by the LatimerCoreScheme, and the rules relating to its application. [http://rs.tdwg.org/ltc/terms/SchemeMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_measurement_or_fact."schemeMeasurementOrFact_pk" IS 'A unique identifier for an ltc:SchemeMeasurementOrFact. [http://example.com/term-pending/schemeMeasurementOrFactID]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_measurement_or_fact."latimerCoreScheme_fk" IS 'An identifier for an ltc:LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/hasSchemeMeasurementOrFact]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_measurement_or_fact."isMandatoryMetric" IS 'A flag to designate whether it is mandatory or optional for every collection description within the LatimerCoreScheme to include the measurement or fact defined by the schemeMeasurementType property. [http://rs.tdwg.org/ltc/terms/isMandatoryMetric]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_measurement_or_fact."isRepeatableMetric" IS 'A flag to designate whether multiple instances of the same schemeMeasurementType may be attached to a single entity. [http://rs.tdwg.org/ltc/terms/isRepeatableMetric]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_measurement_or_fact."schemeMeasurementType" IS 'A category of quantitative metric or qualitative fact that can be included in the LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/schemeMeasurementType]';

-- Scheme Term: A Latimer Core term used by the LatimerCoreScheme and the rules relating to its application.
CREATE TABLE ltc_dp_collapsed.scheme_term (
    "schemeTerm_pk" text NOT NULL,
    "latimerCoreScheme_fk" text NOT NULL,
    "isMandatoryTerm" boolean NOT NULL,
    "isRepeatableTerm" boolean NOT NULL,
    "termName" text NOT NULL,
    CONSTRAINT scheme_term_pkey PRIMARY KEY ("schemeTerm_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.scheme_term IS 'A Latimer Core term used by the LatimerCoreScheme and the rules relating to its application. [http://rs.tdwg.org/ltc/terms/SchemeTerm]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_term."schemeTerm_pk" IS 'A unique identifier for an ltc:SchemeTerm. [http://example.com/term-pending/schemeTermID]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_term."latimerCoreScheme_fk" IS 'An identifier for an ltc:LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/hasSchemeTerm]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_term."isMandatoryTerm" IS 'A flag to designate whether it is mandatory or optional for all ObjectGroups in the LatimerCoreScheme to include or be linked to valid data for the class or property defined in the termName property. [http://rs.tdwg.org/ltc/terms/isMandatoryTerm]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_term."isRepeatableTerm" IS 'A flag to designate whether multiple instances of the Latimer Core class or property defined in the termName property may be attached to a single ObjectGroup. [http://rs.tdwg.org/ltc/terms/isRepeatableTerm]';
COMMENT ON COLUMN ltc_dp_collapsed.scheme_term."termName" IS 'The name of a class or property within the Latimer Core standard that is included in the LatimerCoreScheme. [http://rs.tdwg.org/ltc/terms/termName]';

-- Storage Location: A physical location (such as a building, room, cabinet or drawer) within the holding institution where objects associated with the collection description are stored or exhibited.
CREATE TABLE ltc_dp_collapsed.storage_location (
    "storageLocation_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "parentStorageLocation_fk" text NOT NULL,
    "locationDescription" text,
    "locationName" text NOT NULL,
    "locationType" text,
    CONSTRAINT storage_location_pkey PRIMARY KEY ("storageLocation_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.storage_location IS 'A physical location (such as a building, room, cabinet or drawer) within the holding institution where objects associated with the collection description are stored or exhibited. [http://rs.tdwg.org/ltc/terms/StorageLocation]';
COMMENT ON COLUMN ltc_dp_collapsed.storage_location."storageLocation_pk" IS 'A unique identifier for an ltc:StorageLocation. [http://example.com/term-pending/storageLocationID]';
COMMENT ON COLUMN ltc_dp_collapsed.storage_location."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasStorageLocation]';
COMMENT ON COLUMN ltc_dp_collapsed.storage_location."parentStorageLocation_fk" IS 'An identifier for an ltc:StorageLocation. [http://rs.tdwg.org/ltc/terms/hasParentStorageLocation]';
COMMENT ON COLUMN ltc_dp_collapsed.storage_location."locationDescription" IS 'Short textual description of the storage location of the group of items [http://rs.tdwg.org/ltc/terms/locationDescription]';
COMMENT ON COLUMN ltc_dp_collapsed.storage_location."locationName" IS 'A label used to identify a place where the collection is stored. [http://rs.tdwg.org/ltc/terms/locationName]';
COMMENT ON COLUMN ltc_dp_collapsed.storage_location."locationType" IS 'The nature of the location where the collection is stored. [http://rs.tdwg.org/ltc/terms/locationType]';

-- Taxon: A group of organisms (sensu http://purl.obolibrary.org/obo/OBI_0100026) considered by taxonomists to form a homogeneous unit.
CREATE TABLE ltc_dp_collapsed.taxon (
    "taxon_pk" text NOT NULL,
    "objectGroup_fk" text NOT NULL,
    "genus" text,
    "kingdom" text,
    "scientificName" text,
    "taxonRank" text,
    CONSTRAINT taxon_pkey PRIMARY KEY ("taxon_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.taxon IS 'A group of organisms (sensu http://purl.obolibrary.org/obo/OBI_0100026) considered by taxonomists to form a homogeneous unit. [http://rs.tdwg.org/ltc/terms/Taxon]';
COMMENT ON COLUMN ltc_dp_collapsed.taxon."taxon_pk" IS 'A unique identifier for an ltc:Taxon. [http://example.com/term-pending/taxonID]';
COMMENT ON COLUMN ltc_dp_collapsed.taxon."objectGroup_fk" IS 'An identifier for an ltc:ObjectGroup. [http://rs.tdwg.org/ltc/terms/hasTaxon]';
COMMENT ON COLUMN ltc_dp_collapsed.taxon."genus" IS 'The full scientific name of the genus in which the taxon is classified. [http://rs.tdwg.org/dwc/terms/genus]';
COMMENT ON COLUMN ltc_dp_collapsed.taxon."kingdom" IS 'The full scientific name of the kingdom in which the taxon is classified. [http://rs.tdwg.org/dwc/terms/kingdom]';
COMMENT ON COLUMN ltc_dp_collapsed.taxon."scientificName" IS 'The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term. [http://rs.tdwg.org/dwc/terms/scientificName]';
COMMENT ON COLUMN ltc_dp_collapsed.taxon."taxonRank" IS 'The taxonomic rank of the most specific name in the scientificName. [http://rs.tdwg.org/dwc/terms/taxonRank]';

-- Temporal Coverage: The time period during which the related event, activity or status was occurring.
CREATE TABLE ltc_dp_collapsed.temporal_coverage (
    "temporalCoverage_pk" text NOT NULL,
    "collectionStatusHistory_fk" text,
    "event_fk" text,
    "personRole_fk" text,
    "temporalCoverageEndDateTime" text,
    "temporalCoverageStartDateTime" text,
    "temporalCoverageType" text,
    CONSTRAINT temporal_coverage_pkey PRIMARY KEY ("temporalCoverage_pk")
);
COMMENT ON TABLE ltc_dp_collapsed.temporal_coverage IS 'The time period during which the related event, activity or status was occurring. [http://rs.tdwg.org/ltc/terms/TemporalCoverage]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."temporalCoverage_pk" IS 'A unique identifier for an ltc:TemporalCoverage. [http://example.com/term-pending/temporalCoverageID]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."collectionStatusHistory_fk" IS 'An identifier for an ltc:CollectionStatusHistory. [http://rs.tdwg.org/ltc/terms/hasTemporalCoverage]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."event_fk" IS 'An identifier for an ltc:Event. [http://rs.tdwg.org/ltc/terms/hasTemporalCoverage]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."personRole_fk" IS 'An identifier for an ltc:PersonRole. [http://rs.tdwg.org/ltc/terms/hasTemporalCoverage]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."temporalCoverageEndDateTime" IS 'Datetime at which the TemporalCoverage finished. [http://rs.tdwg.org/ltc/terms/temporalCoverageEndDateTime]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."temporalCoverageStartDateTime" IS 'Datetime at which the TemporalCoverage began. [http://rs.tdwg.org/ltc/terms/temporalCoverageStartDateTime]';
COMMENT ON COLUMN ltc_dp_collapsed.temporal_coverage."temporalCoverageType" IS 'The type or context of the described TemporalCoverage. [http://rs.tdwg.org/ltc/terms/temporalCoverageType]';

-- -------------------------------------------------------------- junction tables


-- ---------------------------------------------------------------- foreign keys


ALTER TABLE ltc_dp_collapsed.address ADD CONSTRAINT address_organisationalunit_fk_fkey FOREIGN KEY ("organisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX address_organisationalunit_fk_idx ON ltc_dp_collapsed.address ("organisationalUnit_fk");
ALTER TABLE ltc_dp_collapsed.address ADD CONSTRAINT address_person_fk_fkey FOREIGN KEY ("person_fk") REFERENCES ltc_dp_collapsed.person ("person_pk");
CREATE INDEX address_person_fk_idx ON ltc_dp_collapsed.address ("person_fk");
ALTER TABLE ltc_dp_collapsed.address ADD CONSTRAINT address_personrole_fk_fkey FOREIGN KEY ("personRole_fk") REFERENCES ltc_dp_collapsed.person_role ("personRole_pk");
CREATE INDEX address_personrole_fk_idx ON ltc_dp_collapsed.address ("personRole_fk");
ALTER TABLE ltc_dp_collapsed.address ADD CONSTRAINT address_storagelocation_fk_fkey FOREIGN KEY ("storageLocation_fk") REFERENCES ltc_dp_collapsed.storage_location ("storageLocation_pk");
CREATE INDEX address_storagelocation_fk_idx ON ltc_dp_collapsed.address ("storageLocation_fk");

ALTER TABLE ltc_dp_collapsed.chronometric_age ADD CONSTRAINT chronometric_age_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX chronometric_age_objectgroup_fk_idx ON ltc_dp_collapsed.chronometric_age ("objectGroup_fk");

ALTER TABLE ltc_dp_collapsed.collection_status_history ADD CONSTRAINT collection_status_history_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX collection_status_history_objectgroup_fk_idx ON ltc_dp_collapsed.collection_status_history ("objectGroup_fk");

ALTER TABLE ltc_dp_collapsed.contact_detail ADD CONSTRAINT contact_detail_organisationalunit_fk_fkey FOREIGN KEY ("organisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX contact_detail_organisationalunit_fk_idx ON ltc_dp_collapsed.contact_detail ("organisationalUnit_fk");
ALTER TABLE ltc_dp_collapsed.contact_detail ADD CONSTRAINT contact_detail_person_fk_fkey FOREIGN KEY ("person_fk") REFERENCES ltc_dp_collapsed.person ("person_pk");
CREATE INDEX contact_detail_person_fk_idx ON ltc_dp_collapsed.contact_detail ("person_fk");
ALTER TABLE ltc_dp_collapsed.contact_detail ADD CONSTRAINT contact_detail_personrole_fk_fkey FOREIGN KEY ("personRole_fk") REFERENCES ltc_dp_collapsed.person_role ("personRole_pk");
CREATE INDEX contact_detail_personrole_fk_idx ON ltc_dp_collapsed.contact_detail ("personRole_fk");

ALTER TABLE ltc_dp_collapsed.ecological_context ADD CONSTRAINT ecological_context_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX ecological_context_event_fk_idx ON ltc_dp_collapsed.ecological_context ("event_fk");
ALTER TABLE ltc_dp_collapsed.ecological_context ADD CONSTRAINT ecological_context_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX ecological_context_objectgroup_fk_idx ON ltc_dp_collapsed.ecological_context ("objectGroup_fk");

ALTER TABLE ltc_dp_collapsed.event ADD CONSTRAINT event_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX event_objectgroup_fk_idx ON ltc_dp_collapsed.event ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.event ADD CONSTRAINT event_parentevent_fk_fkey FOREIGN KEY ("parentEvent_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX event_parentevent_fk_idx ON ltc_dp_collapsed.event ("parentEvent_fk");

ALTER TABLE ltc_dp_collapsed.geographic_context ADD CONSTRAINT geographic_context_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX geographic_context_event_fk_idx ON ltc_dp_collapsed.geographic_context ("event_fk");
ALTER TABLE ltc_dp_collapsed.geographic_context ADD CONSTRAINT geographic_context_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX geographic_context_objectgroup_fk_idx ON ltc_dp_collapsed.geographic_context ("objectGroup_fk");

ALTER TABLE ltc_dp_collapsed.geological_context ADD CONSTRAINT geological_context_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX geological_context_objectgroup_fk_idx ON ltc_dp_collapsed.geological_context ("objectGroup_fk");

ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_address_fk_fkey FOREIGN KEY ("address_fk") REFERENCES ltc_dp_collapsed.address ("address_pk");
CREATE INDEX identifier_address_fk_idx ON ltc_dp_collapsed.identifier ("address_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_chronometricage_fk_fkey FOREIGN KEY ("chronometricAge_fk") REFERENCES ltc_dp_collapsed.chronometric_age ("chronometricAge_pk");
CREATE INDEX identifier_chronometricage_fk_idx ON ltc_dp_collapsed.identifier ("chronometricAge_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_collectionstatushistory_fk_fkey FOREIGN KEY ("collectionStatusHistory_fk") REFERENCES ltc_dp_collapsed.collection_status_history ("collectionStatusHistory_pk");
CREATE INDEX identifier_collectionstatushistory_fk_idx ON ltc_dp_collapsed.identifier ("collectionStatusHistory_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_contactdetail_fk_fkey FOREIGN KEY ("contactDetail_fk") REFERENCES ltc_dp_collapsed.contact_detail ("contactDetail_pk");
CREATE INDEX identifier_contactdetail_fk_idx ON ltc_dp_collapsed.identifier ("contactDetail_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_ecologicalcontext_fk_fkey FOREIGN KEY ("ecologicalContext_fk") REFERENCES ltc_dp_collapsed.ecological_context ("ecologicalContext_pk");
CREATE INDEX identifier_ecologicalcontext_fk_idx ON ltc_dp_collapsed.identifier ("ecologicalContext_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX identifier_event_fk_idx ON ltc_dp_collapsed.identifier ("event_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_geographiccontext_fk_fkey FOREIGN KEY ("geographicContext_fk") REFERENCES ltc_dp_collapsed.geographic_context ("geographicContext_pk");
CREATE INDEX identifier_geographiccontext_fk_idx ON ltc_dp_collapsed.identifier ("geographicContext_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_geologicalcontext_fk_fkey FOREIGN KEY ("geologicalContext_fk") REFERENCES ltc_dp_collapsed.geological_context ("geologicalContext_pk");
CREATE INDEX identifier_geologicalcontext_fk_idx ON ltc_dp_collapsed.identifier ("geologicalContext_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_latimercorescheme_fk_fkey FOREIGN KEY ("latimerCoreScheme_fk") REFERENCES ltc_dp_collapsed.latimer_core_scheme ("latimerCoreScheme_pk");
CREATE INDEX identifier_latimercorescheme_fk_idx ON ltc_dp_collapsed.identifier ("latimerCoreScheme_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_measurementorfact_fk_fkey FOREIGN KEY ("measurementOrFact_fk") REFERENCES ltc_dp_collapsed.measurement_or_fact ("measurementOrFact_pk");
CREATE INDEX identifier_measurementorfact_fk_idx ON ltc_dp_collapsed.identifier ("measurementOrFact_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_objectclassification_fk_fkey FOREIGN KEY ("objectClassification_fk") REFERENCES ltc_dp_collapsed.object_classification ("objectClassification_pk");
CREATE INDEX identifier_objectclassification_fk_idx ON ltc_dp_collapsed.identifier ("objectClassification_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX identifier_objectgroup_fk_idx ON ltc_dp_collapsed.identifier ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_organisationalunit_fk_fkey FOREIGN KEY ("organisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX identifier_organisationalunit_fk_idx ON ltc_dp_collapsed.identifier ("organisationalUnit_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_person_fk_fkey FOREIGN KEY ("person_fk") REFERENCES ltc_dp_collapsed.person ("person_pk");
CREATE INDEX identifier_person_fk_idx ON ltc_dp_collapsed.identifier ("person_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_personrole_fk_fkey FOREIGN KEY ("personRole_fk") REFERENCES ltc_dp_collapsed.person_role ("personRole_pk");
CREATE INDEX identifier_personrole_fk_idx ON ltc_dp_collapsed.identifier ("personRole_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_recordlevel_fk_fkey FOREIGN KEY ("recordLevel_fk") REFERENCES ltc_dp_collapsed.record_level ("recordLevel_pk");
CREATE INDEX identifier_recordlevel_fk_idx ON ltc_dp_collapsed.identifier ("recordLevel_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_reference_fk_fkey FOREIGN KEY ("reference_fk") REFERENCES ltc_dp_collapsed.reference ("reference_pk");
CREATE INDEX identifier_reference_fk_idx ON ltc_dp_collapsed.identifier ("reference_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_resourcerelationship_fk_fkey FOREIGN KEY ("resourceRelationship_fk") REFERENCES ltc_dp_collapsed.resource_relationship ("resourceRelationship_pk");
CREATE INDEX identifier_resourcerelationship_fk_idx ON ltc_dp_collapsed.identifier ("resourceRelationship_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_role_fk_fkey FOREIGN KEY ("role_fk") REFERENCES ltc_dp_collapsed.role ("role_pk");
CREATE INDEX identifier_role_fk_idx ON ltc_dp_collapsed.identifier ("role_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_schememeasurementorfact_fk_fkey FOREIGN KEY ("schemeMeasurementOrFact_fk") REFERENCES ltc_dp_collapsed.scheme_measurement_or_fact ("schemeMeasurementOrFact_pk");
CREATE INDEX identifier_schememeasurementorfact_fk_idx ON ltc_dp_collapsed.identifier ("schemeMeasurementOrFact_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_schemeterm_fk_fkey FOREIGN KEY ("schemeTerm_fk") REFERENCES ltc_dp_collapsed.scheme_term ("schemeTerm_pk");
CREATE INDEX identifier_schemeterm_fk_idx ON ltc_dp_collapsed.identifier ("schemeTerm_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_storagelocation_fk_fkey FOREIGN KEY ("storageLocation_fk") REFERENCES ltc_dp_collapsed.storage_location ("storageLocation_pk");
CREATE INDEX identifier_storagelocation_fk_idx ON ltc_dp_collapsed.identifier ("storageLocation_fk");
ALTER TABLE ltc_dp_collapsed.identifier ADD CONSTRAINT identifier_taxon_fk_fkey FOREIGN KEY ("taxon_fk") REFERENCES ltc_dp_collapsed.taxon ("taxon_pk");
CREATE INDEX identifier_taxon_fk_idx ON ltc_dp_collapsed.identifier ("taxon_fk");

ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_chronometricage_fk_fkey FOREIGN KEY ("chronometricAge_fk") REFERENCES ltc_dp_collapsed.chronometric_age ("chronometricAge_pk");
CREATE INDEX measurement_or_fact_chronometricage_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("chronometricAge_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_collectionstatushistory_fk_fkey FOREIGN KEY ("collectionStatusHistory_fk") REFERENCES ltc_dp_collapsed.collection_status_history ("collectionStatusHistory_pk");
CREATE INDEX measurement_or_fact_collectionstatushistory_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("collectionStatusHistory_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_ecologicalcontext_fk_fkey FOREIGN KEY ("ecologicalContext_fk") REFERENCES ltc_dp_collapsed.ecological_context ("ecologicalContext_pk");
CREATE INDEX measurement_or_fact_ecologicalcontext_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("ecologicalContext_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX measurement_or_fact_event_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("event_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_geographiccontext_fk_fkey FOREIGN KEY ("geographicContext_fk") REFERENCES ltc_dp_collapsed.geographic_context ("geographicContext_pk");
CREATE INDEX measurement_or_fact_geographiccontext_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("geographicContext_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_geologicalcontext_fk_fkey FOREIGN KEY ("geologicalContext_fk") REFERENCES ltc_dp_collapsed.geological_context ("geologicalContext_pk");
CREATE INDEX measurement_or_fact_geologicalcontext_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("geologicalContext_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_objectclassification_fk_fkey FOREIGN KEY ("objectClassification_fk") REFERENCES ltc_dp_collapsed.object_classification ("objectClassification_pk");
CREATE INDEX measurement_or_fact_objectclassification_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("objectClassification_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX measurement_or_fact_objectgroup_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_organisationalunit_fk_fkey FOREIGN KEY ("organisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX measurement_or_fact_organisationalunit_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("organisationalUnit_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_person_fk_fkey FOREIGN KEY ("person_fk") REFERENCES ltc_dp_collapsed.person ("person_pk");
CREATE INDEX measurement_or_fact_person_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("person_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_personrole_fk_fkey FOREIGN KEY ("personRole_fk") REFERENCES ltc_dp_collapsed.person_role ("personRole_pk");
CREATE INDEX measurement_or_fact_personrole_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("personRole_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_resourcerelationship_fk_fkey FOREIGN KEY ("resourceRelationship_fk") REFERENCES ltc_dp_collapsed.resource_relationship ("resourceRelationship_pk");
CREATE INDEX measurement_or_fact_resourcerelationship_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("resourceRelationship_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_storagelocation_fk_fkey FOREIGN KEY ("storageLocation_fk") REFERENCES ltc_dp_collapsed.storage_location ("storageLocation_pk");
CREATE INDEX measurement_or_fact_storagelocation_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("storageLocation_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_taxon_fk_fkey FOREIGN KEY ("taxon_fk") REFERENCES ltc_dp_collapsed.taxon ("taxon_pk");
CREATE INDEX measurement_or_fact_taxon_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("taxon_fk");
ALTER TABLE ltc_dp_collapsed.measurement_or_fact ADD CONSTRAINT measurement_or_fact_temporalcoverage_fk_fkey FOREIGN KEY ("temporalCoverage_fk") REFERENCES ltc_dp_collapsed.temporal_coverage ("temporalCoverage_pk");
CREATE INDEX measurement_or_fact_temporalcoverage_fk_idx ON ltc_dp_collapsed.measurement_or_fact ("temporalCoverage_fk");

ALTER TABLE ltc_dp_collapsed.object_classification ADD CONSTRAINT object_classification_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX object_classification_objectgroup_fk_idx ON ltc_dp_collapsed.object_classification ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.object_classification ADD CONSTRAINT object_classification_parentobjectclassification_fk_fkey FOREIGN KEY ("parentObjectClassification_fk") REFERENCES ltc_dp_collapsed.object_classification ("objectClassification_pk");
CREATE INDEX object_classification_parentobjectclassification_fk_idx ON ltc_dp_collapsed.object_classification ("parentObjectClassification_fk");

ALTER TABLE ltc_dp_collapsed.object_group ADD CONSTRAINT object_group_latimercorescheme_fk_fkey FOREIGN KEY ("latimerCoreScheme_fk") REFERENCES ltc_dp_collapsed.latimer_core_scheme ("latimerCoreScheme_pk");
CREATE INDEX object_group_latimercorescheme_fk_idx ON ltc_dp_collapsed.object_group ("latimerCoreScheme_fk");
ALTER TABLE ltc_dp_collapsed.object_group ADD CONSTRAINT object_group_recordlevel_fk_fkey FOREIGN KEY ("recordLevel_fk") REFERENCES ltc_dp_collapsed.record_level ("recordLevel_pk");
CREATE INDEX object_group_recordlevel_fk_idx ON ltc_dp_collapsed.object_group ("recordLevel_fk");

ALTER TABLE ltc_dp_collapsed.organisational_unit ADD CONSTRAINT organisational_unit_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX organisational_unit_objectgroup_fk_idx ON ltc_dp_collapsed.organisational_unit ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.organisational_unit ADD CONSTRAINT organisational_unit_parentorganisationalunit_fk_fkey FOREIGN KEY ("parentOrganisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX organisational_unit_parentorganisationalunit_fk_idx ON ltc_dp_collapsed.organisational_unit ("parentOrganisationalUnit_fk");

ALTER TABLE ltc_dp_collapsed.person_role ADD CONSTRAINT person_role_person_fk_fkey FOREIGN KEY ("person_fk") REFERENCES ltc_dp_collapsed.person ("person_pk");
CREATE INDEX person_role_person_fk_idx ON ltc_dp_collapsed.person_role ("person_fk");
ALTER TABLE ltc_dp_collapsed.person_role ADD CONSTRAINT person_role_role_fk_fkey FOREIGN KEY ("role_fk") REFERENCES ltc_dp_collapsed.role ("role_pk");
CREATE INDEX person_role_role_fk_idx ON ltc_dp_collapsed.person_role ("role_fk");
ALTER TABLE ltc_dp_collapsed.person_role ADD CONSTRAINT person_role_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX person_role_event_fk_idx ON ltc_dp_collapsed.person_role ("event_fk");
ALTER TABLE ltc_dp_collapsed.person_role ADD CONSTRAINT person_role_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX person_role_objectgroup_fk_idx ON ltc_dp_collapsed.person_role ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.person_role ADD CONSTRAINT person_role_organisationalunit_fk_fkey FOREIGN KEY ("organisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX person_role_organisationalunit_fk_idx ON ltc_dp_collapsed.person_role ("organisationalUnit_fk");
ALTER TABLE ltc_dp_collapsed.person_role ADD CONSTRAINT person_role_recordlevel_fk_fkey FOREIGN KEY ("recordLevel_fk") REFERENCES ltc_dp_collapsed.record_level ("recordLevel_pk");
CREATE INDEX person_role_recordlevel_fk_idx ON ltc_dp_collapsed.person_role ("recordLevel_fk");

ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_chronometricage_fk_fkey FOREIGN KEY ("chronometricAge_fk") REFERENCES ltc_dp_collapsed.chronometric_age ("chronometricAge_pk");
CREATE INDEX reference_chronometricage_fk_idx ON ltc_dp_collapsed.reference ("chronometricAge_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_collectionstatushistory_fk_fkey FOREIGN KEY ("collectionStatusHistory_fk") REFERENCES ltc_dp_collapsed.collection_status_history ("collectionStatusHistory_pk");
CREATE INDEX reference_collectionstatushistory_fk_idx ON ltc_dp_collapsed.reference ("collectionStatusHistory_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_ecologicalcontext_fk_fkey FOREIGN KEY ("ecologicalContext_fk") REFERENCES ltc_dp_collapsed.ecological_context ("ecologicalContext_pk");
CREATE INDEX reference_ecologicalcontext_fk_idx ON ltc_dp_collapsed.reference ("ecologicalContext_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX reference_event_fk_idx ON ltc_dp_collapsed.reference ("event_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_geographiccontext_fk_fkey FOREIGN KEY ("geographicContext_fk") REFERENCES ltc_dp_collapsed.geographic_context ("geographicContext_pk");
CREATE INDEX reference_geographiccontext_fk_idx ON ltc_dp_collapsed.reference ("geographicContext_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_geologicalcontext_fk_fkey FOREIGN KEY ("geologicalContext_fk") REFERENCES ltc_dp_collapsed.geological_context ("geologicalContext_pk");
CREATE INDEX reference_geologicalcontext_fk_idx ON ltc_dp_collapsed.reference ("geologicalContext_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_identifier_fk_fkey FOREIGN KEY ("identifier_fk") REFERENCES ltc_dp_collapsed.identifier ("identifier_pk");
CREATE INDEX reference_identifier_fk_idx ON ltc_dp_collapsed.reference ("identifier_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_latimercorescheme_fk_fkey FOREIGN KEY ("latimerCoreScheme_fk") REFERENCES ltc_dp_collapsed.latimer_core_scheme ("latimerCoreScheme_pk");
CREATE INDEX reference_latimercorescheme_fk_idx ON ltc_dp_collapsed.reference ("latimerCoreScheme_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_measurementorfact_fk_fkey FOREIGN KEY ("measurementOrFact_fk") REFERENCES ltc_dp_collapsed.measurement_or_fact ("measurementOrFact_pk");
CREATE INDEX reference_measurementorfact_fk_idx ON ltc_dp_collapsed.reference ("measurementOrFact_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_objectclassification_fk_fkey FOREIGN KEY ("objectClassification_fk") REFERENCES ltc_dp_collapsed.object_classification ("objectClassification_pk");
CREATE INDEX reference_objectclassification_fk_idx ON ltc_dp_collapsed.reference ("objectClassification_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX reference_objectgroup_fk_idx ON ltc_dp_collapsed.reference ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_organisationalunit_fk_fkey FOREIGN KEY ("organisationalUnit_fk") REFERENCES ltc_dp_collapsed.organisational_unit ("organisationalUnit_pk");
CREATE INDEX reference_organisationalunit_fk_idx ON ltc_dp_collapsed.reference ("organisationalUnit_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_person_fk_fkey FOREIGN KEY ("person_fk") REFERENCES ltc_dp_collapsed.person ("person_pk");
CREATE INDEX reference_person_fk_idx ON ltc_dp_collapsed.reference ("person_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_personrole_fk_fkey FOREIGN KEY ("personRole_fk") REFERENCES ltc_dp_collapsed.person_role ("personRole_pk");
CREATE INDEX reference_personrole_fk_idx ON ltc_dp_collapsed.reference ("personRole_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_recordlevel_fk_fkey FOREIGN KEY ("recordLevel_fk") REFERENCES ltc_dp_collapsed.record_level ("recordLevel_pk");
CREATE INDEX reference_recordlevel_fk_idx ON ltc_dp_collapsed.reference ("recordLevel_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_resourcerelationship_fk_fkey FOREIGN KEY ("resourceRelationship_fk") REFERENCES ltc_dp_collapsed.resource_relationship ("resourceRelationship_pk");
CREATE INDEX reference_resourcerelationship_fk_idx ON ltc_dp_collapsed.reference ("resourceRelationship_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_schememeasurementorfact_fk_fkey FOREIGN KEY ("schemeMeasurementOrFact_fk") REFERENCES ltc_dp_collapsed.scheme_measurement_or_fact ("schemeMeasurementOrFact_pk");
CREATE INDEX reference_schememeasurementorfact_fk_idx ON ltc_dp_collapsed.reference ("schemeMeasurementOrFact_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_schemeterm_fk_fkey FOREIGN KEY ("schemeTerm_fk") REFERENCES ltc_dp_collapsed.scheme_term ("schemeTerm_pk");
CREATE INDEX reference_schemeterm_fk_idx ON ltc_dp_collapsed.reference ("schemeTerm_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_storagelocation_fk_fkey FOREIGN KEY ("storageLocation_fk") REFERENCES ltc_dp_collapsed.storage_location ("storageLocation_pk");
CREATE INDEX reference_storagelocation_fk_idx ON ltc_dp_collapsed.reference ("storageLocation_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_taxon_fk_fkey FOREIGN KEY ("taxon_fk") REFERENCES ltc_dp_collapsed.taxon ("taxon_pk");
CREATE INDEX reference_taxon_fk_idx ON ltc_dp_collapsed.reference ("taxon_fk");
ALTER TABLE ltc_dp_collapsed.reference ADD CONSTRAINT reference_temporalcoverage_fk_fkey FOREIGN KEY ("temporalCoverage_fk") REFERENCES ltc_dp_collapsed.temporal_coverage ("temporalCoverage_pk");
CREATE INDEX reference_temporalcoverage_fk_idx ON ltc_dp_collapsed.reference ("temporalCoverage_fk");

ALTER TABLE ltc_dp_collapsed.resource_relationship ADD CONSTRAINT resource_relationship_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX resource_relationship_objectgroup_fk_idx ON ltc_dp_collapsed.resource_relationship ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.resource_relationship ADD CONSTRAINT resource_relationship_recordlevel_fk_fkey FOREIGN KEY ("recordLevel_fk") REFERENCES ltc_dp_collapsed.record_level ("recordLevel_pk");
CREATE INDEX resource_relationship_recordlevel_fk_idx ON ltc_dp_collapsed.resource_relationship ("recordLevel_fk");

ALTER TABLE ltc_dp_collapsed.scheme_measurement_or_fact ADD CONSTRAINT scheme_measurement_or_fact_latimercorescheme_fk_fkey FOREIGN KEY ("latimerCoreScheme_fk") REFERENCES ltc_dp_collapsed.latimer_core_scheme ("latimerCoreScheme_pk");
CREATE INDEX scheme_measurement_or_fact_latimercorescheme_fk_idx ON ltc_dp_collapsed.scheme_measurement_or_fact ("latimerCoreScheme_fk");

ALTER TABLE ltc_dp_collapsed.scheme_term ADD CONSTRAINT scheme_term_latimercorescheme_fk_fkey FOREIGN KEY ("latimerCoreScheme_fk") REFERENCES ltc_dp_collapsed.latimer_core_scheme ("latimerCoreScheme_pk");
CREATE INDEX scheme_term_latimercorescheme_fk_idx ON ltc_dp_collapsed.scheme_term ("latimerCoreScheme_fk");

ALTER TABLE ltc_dp_collapsed.storage_location ADD CONSTRAINT storage_location_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX storage_location_objectgroup_fk_idx ON ltc_dp_collapsed.storage_location ("objectGroup_fk");
ALTER TABLE ltc_dp_collapsed.storage_location ADD CONSTRAINT storage_location_parentstoragelocation_fk_fkey FOREIGN KEY ("parentStorageLocation_fk") REFERENCES ltc_dp_collapsed.storage_location ("storageLocation_pk");
CREATE INDEX storage_location_parentstoragelocation_fk_idx ON ltc_dp_collapsed.storage_location ("parentStorageLocation_fk");

ALTER TABLE ltc_dp_collapsed.taxon ADD CONSTRAINT taxon_objectgroup_fk_fkey FOREIGN KEY ("objectGroup_fk") REFERENCES ltc_dp_collapsed.object_group ("objectGroup_pk");
CREATE INDEX taxon_objectgroup_fk_idx ON ltc_dp_collapsed.taxon ("objectGroup_fk");

ALTER TABLE ltc_dp_collapsed.temporal_coverage ADD CONSTRAINT temporal_coverage_collectionstatushistory_fk_fkey FOREIGN KEY ("collectionStatusHistory_fk") REFERENCES ltc_dp_collapsed.collection_status_history ("collectionStatusHistory_pk");
CREATE INDEX temporal_coverage_collectionstatushistory_fk_idx ON ltc_dp_collapsed.temporal_coverage ("collectionStatusHistory_fk");
ALTER TABLE ltc_dp_collapsed.temporal_coverage ADD CONSTRAINT temporal_coverage_event_fk_fkey FOREIGN KEY ("event_fk") REFERENCES ltc_dp_collapsed.event ("event_pk");
CREATE INDEX temporal_coverage_event_fk_idx ON ltc_dp_collapsed.temporal_coverage ("event_fk");
ALTER TABLE ltc_dp_collapsed.temporal_coverage ADD CONSTRAINT temporal_coverage_personrole_fk_fkey FOREIGN KEY ("personRole_fk") REFERENCES ltc_dp_collapsed.person_role ("personRole_pk");
CREATE INDEX temporal_coverage_personrole_fk_idx ON ltc_dp_collapsed.temporal_coverage ("personRole_fk");

COMMIT;
